// Presentation layer exports
export * from './components/Header';
export * from './components/Layout';
export * from './components/SEO';
export * from './components/sections/IntroSection';
export * from './components/sections/ProjectsSection';
export * from './components/sections/ExperienceSection';
export * from './components/sections/CertificatesSection';
export * from './components/sections/FooterSection';
export * from './pages/HomePage';
export * from './hooks/useTheme';
export * from './hooks/useAnalytics';
export * from './hooks/useAccessibility';
